### PR TITLE
Recipes and mass balancing

### PR DESCRIPTION
**Pull request by millennIumAMbiguity**
The furnace is 2800 and blast_furnace is 3000, therefor I believe it's appropriate for the engine to be 3200.
The anchor is iron block + 1000.

### CODE REVIEW

**Comment by millennIumAMbiguity** [comment]
Please speak your minds about this. Even if it's not a change suggestion, please discuss any balancing concerns and ideas.

**Comment by copperwarrior** [comment]
I think these masses are fine. There is a point to be made about these common parts being too heavy to operate a ship, but I can't imagine that it's that big of a problem.

**Comment by millennIumAMbiguity** [comment]
> I think these masses are fine. There is a point to be made about these common parts being too heavy to operate a ship, but I can't imagine that it's that big of a problem.


Made an airship using 4 balloons holding up the anchor. If anything it's still too easy and the balloons should get nerf'd. 

image

**Comment by copperwarrior** [comment]
Then I see no problem with this. Eureka is meant to be very easy to use and operate, and it is very configurable for the servers that do not want that.

**Comment by millennIumAMbiguity** [comment]
Yes, that is why I have not changed that. but I belive a slight change might make it better. 👍

**Review by Rubydesic — APPROVED** [review]
lgtm

**Comment by ewoudje** [comment]
idk about the lead in the recipe, getting leads can be difficult. or you have some luck and meet a wandering trader and you can make 2 leads or you need to get slime wich sometimes is very hard.

**Comment by ewoudje** [comment]
The balloon amounts seem to me a bit extreme. While i understand that 4 strings shoudln't give allot of balloons strings are more expensive then wool in the game. that recipe seems useless based on the cost and return. For the wool imo its also extreme, i imaigne a casual player with a sheep farm of 8 big in a nice fence. This would mean that each shearing would only produce 16 balloons, this sounds too harsh for me. I agree with that the leather should have more balloon, but 14 balloons is odd. Also it would be cool to have leather make brown balloons.

**Comment by millennIumAMbiguity** [comment]
> The balloon amounts seem to me a bit extreme. While i understand that 4 strings shoudln't give allot of balloons strings are more expensive then wool in the game. that recipe seems useless based on the cost and return. For the wool imo its also extreme, i imaigne a casual player with a sheep farm of 8 big in a nice fence. This would mean that each shearing would only produce 16 balloons, this sounds too harsh for me. I agree with that the leather should have more balloon, but 14 balloons is odd. Also it would be cool to have leather make brown balloons.

I have been playing around in a survival world and found the numbers work well, the string recipe is not about the rarity of string but an option if you don't have the resources to craft it any other way. In my survival work, I was out of all others, but I needed some balloons for a quick nether transportation, the string I had on hand was above enough.

You can build a ship with just one balloon. I imagine that if one wants to have an oversized balloon or giant ship, one would build a farm to gather those resources. Strings are very common to find and are not an optimal resource to craft balloons.

Leather gives 14 because phantom membrane gives 16. the phantom membrane is way harder to farm or find.

> idk about the lead in the recipe, getting leads can be difficult. or you have some luck and meet a wandering trader and you can make 2 leads or you need to get slime which sometimes is very hard.

The anchor is not necessary to have on your ships. Therefore it does not matter if it's a little harder to get your hands on one. slime can be commonly found in dungeon chests or can be hunted in slime chunks or swamps. Additanly, the traveling merchant is not only very common but also drops two leads when killed.

looking forward to hearing back.

**Comment by ewoudje** [comment]
I suppose the string recipe is fair. Also you are right about the anchor, I suppose its not a must thus indeed not too harsh to make it need something more rare. 

I get that you would expand the farm based on the need of balloons but I still feel like 4 to 8 is not enough.
But maybe this is just me. Il do a poll in vs2 to choose that.

**Comment by ewoudje** [comment]
Ok so the poll results are:
Wool 4
Membrane 32
Leather 4 (we need to make it start with brown color but also a way to wash? the balloon back)
Paper 2
String none (in the poll i said "the results *can* change the recipes not will we can keep it if we want so)

**Comment by millennIumAMbiguity** [comment]
> Ok so the poll results are: Wool 4 Membrane 32 Leather 4 (we need to make it start with brown color but also a way to wash? the balloon back) Paper 2 String none (in the poll I said "the results _can_ change the recipes not will we can keep it if we want so)

The brown Leather craft would be restrictive without a way to wash/recolor the ballons. 

Regarding the string recipe, you can craft string into wool.

**Comment by ewoudje** [comment]
Ok time to merge, the leather, and washing can be done in a seperate PR.

**Pull request merged**
