### PR TITLE
New helm model

### PR DESCRIPTION
**Pull request by millennIumAMbiguity**
With the help of [xllifi](https://github.com/xllifi), I have optimized the model file sizes and improved the models.

image

### CODE REVIEW

**Comment by millennIumAMbiguity** [comment]
image

**Comment by copperwarrior** [comment]
This model was FACT CHECKED by TRUE PATRIOTS
🇺🇸 
I approve

**Comment by AlexanderwithaA** [comment]
Did the helm collision box get changed for this?

**Comment by millennIumAMbiguity** [comment]
> Did the helm collision box get changed for this?

no.

**Pull request merged**
