### PR TITLE
fix gradle for some systems

### PR DESCRIPTION
**Pull request by alex-s168**

### CODE REVIEW

**Comment by millennIumAMbiguity** [comment]
What systems is this for?

**Comment by AlexanderwithaA** [comment]
I was getting help from Alex on this, it was broken in my system, win11

**Comment by millennIumAMbiguity** [comment]
> I was getting help from Alex on this, it was broken in my system, win11

do you have git installed?

**Comment by AlexanderwithaA** [comment]
Yes

**Comment by millennIumAMbiguity** [comment]
I am not confident in gradle so I can't say if this is a reasonable change. 
Having the error would help.

**Comment by AlexanderwithaA** [comment]
I discussed it here with Alex https://discord.com/channels/244934352092397568/963564330924777522/1226753443767521331

**Comment by millennIumAMbiguity** [comment]
would it not make sense to use `git rev-parse --short HEAD`?

**Pull request merged**
